### ISSUE TITLE
Detect multiple environments

### ISSUE THREAD

**Issue by aseyboldt** [renan-r-santos/pixi-kernel#20]
If a project has multiple environments (for instance one with gpu and one without), it would be nice if this would show a kernel for each of those environments.

**Comment by roaldarbol** [comment]
I think my issue falls under this one - at least it's also related to the environments. I've tried making a Jupyter `feature`, but the kernel doesn't detect my IRKernel:
```toml
[project]
name = "testing"
version = "0.1.0"
description = "Add a short description here"
authors = ["Your Name <and@email>"]
channels = ["conda-forge", "https://prefix.dev/r-forge/"]
platforms = ["osx-64"]

[tasks]

[dependencies]
r-base = "4.2"

[feature.jupyter.dependencies]
jupyterlab = "*"
pixi-kernel = "*"
r-irkernel = "*"

[environments]
jupyter = ["jupyter"]
```

So the `r-irkernel` is installed within the feature, but it doesn't get detected:
<img width="1071" alt="Screenshot 2024-07-09 at 22 55 59" src="https://github.com/renan-r-santos/pixi-kernel/assets/25629697/0a26a67f-a447-424f-96ff-e2a019594d92">

I open Jupyter with `pixi run -e jupyter jupyter lab`.
